/*
 * build-data.js — turns the raw sources in tools/raw/ into the browser data
 * files in data/. Everything is emitted as `window.DATA_* = ...` so the app
 * works from file:// with no server and no build step.
 *
 * Run with:  node tools/build-data.js
 */
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const RAW = path.join(__dirname, 'raw');
const OUT = path.join(__dirname, '..', 'data');
const read = f => JSON.parse(fs.readFileSync(path.join(RAW, f), 'utf8'));

// --- load d3-geo + topojson into a clean context (their UMD wrappers take the
// CommonJS branch under node, which breaks the d3-array dependency) ---------
const ctx = vm.createContext({});
for (const f of ['d3-array.min.js', 'd3-geo.min.js', 'topojson-client.min.js'])
  vm.runInContext(fs.readFileSync(path.join(__dirname, '..', 'js', 'vendor', f), 'utf8'), ctx);
const d3 = ctx.d3, topojson = ctx.topojson;

function emit(file, varName, value) {
  const body = '// Generated by tools/build-data.js — do not edit by hand.\n'
    + 'window.' + varName + ' = ' + JSON.stringify(value) + ';\n';
  fs.writeFileSync(path.join(OUT, file), body);
  console.log('  data/' + file.padEnd(16) + (body.length / 1024).toFixed(0).padStart(5) + ' KB  ' + varName);
}

function round(features, prec) {
  const r = n => Math.round(n * 10 ** prec) / 10 ** prec;
  const walk = c => Array.isArray(c[0]) ? c.map(walk) : [r(c[0]), r(c[1])];
  for (const f of features) f.geometry.coordinates = walk(f.geometry.coordinates);
}

/* ------------------------------------------------------------------ WORLD */
function buildWorld() {
  const topo = read('world-110m.json');
  const fc = topojson.feature(topo, topo.objects.countries);
  const iso = read('iso.json');
  const byNum = new Map(iso.map(r => [String(+r['country-code']), r]));

  // world-atlas abbreviates some names; spell them out for quiz prompts
  const NAME_FIX = {
    'Dem. Rep. Congo': 'DR Congo',
    'Congo': 'Republic of the Congo',
    'Central African Rep.': 'Central African Republic',
    'Dominican Rep.': 'Dominican Republic',
    'Eq. Guinea': 'Equatorial Guinea',
    'S. Sudan': 'South Sudan',
    'Bosnia and Herz.': 'Bosnia and Herzegovina',
    'Solomon Is.': 'Solomon Islands',
    'Falkland Is.': 'Falkland Islands',
    'Fr. S. Antarctic Lands': 'French Southern Territories',
    'W. Sahara': 'Western Sahara',
    'N. Cyprus': 'Northern Cyprus',
    'United States of America': 'United States',
    'Central African Rep': 'Central African Republic',
  };
  // continent info for entries ISO 3166 does not assign
  const EXTRA = {
    'Somaliland': { region: 'Africa', subregion: 'Sub-Saharan Africa', iso2: 'XS', id: 'XSO' },
    'Kosovo': { region: 'Europe', subregion: 'Southern Europe', iso2: 'XK', id: 'XKX' },
    'Northern Cyprus': { region: 'Asia', subregion: 'Western Asia', iso2: 'XN', id: 'XNC' },
  };
  // ISO 3166 leaves Taiwan's region fields blank; the quiz needs a continent
  const REGION_FIX = { TWN: { region: 'Asia', subregion: 'Eastern Asia' } };

  const features = [];
  for (const f of fc.features) {
    const meta = byNum.get(String(+f.id));
    const rawName = f.properties.name;
    const name = NAME_FIX[rawName] || rawName;
    const extra = EXTRA[name];
    if (!meta && !extra) { console.warn('  ! no ISO metadata for ' + rawName); continue; }
    const id = meta ? meta['alpha-3'] : extra.id;
    const fix = REGION_FIX[id];
    features.push({
      type: 'Feature',
      properties: {
        id: id,
        iso2: meta ? meta['alpha-2'] : extra.iso2,
        name: name,
        region: (fix && fix.region) || (meta ? meta.region : extra.region),
        subregion: (fix && fix.subregion) || (meta ? meta['sub-region'] : extra.subregion),
      },
      geometry: f.geometry,
    });
  }
  // Antarctica is not a country-quiz target
  const out = features.filter(f => f.properties.id !== 'ATA');
  round(out, 2);
  out.sort((a, b) => a.properties.name.localeCompare(b.properties.name));
  emit('world.js', 'DATA_WORLD', { type: 'FeatureCollection', features: out });
  return { type: 'FeatureCollection', features: out };
}

/* ------------------------------------------------------------------ JAPAN */
const JP_REGIONS = {
  Hokkaido: [1],
  Tohoku: [2, 3, 4, 5, 6, 7],
  Kanto: [8, 9, 10, 11, 12, 13, 14],
  Chubu: [15, 16, 17, 18, 19, 20, 21, 22, 23],
  Kansai: [24, 25, 26, 27, 28, 29, 30],
  Chugoku: [31, 32, 33, 34, 35],
  Shikoku: [36, 37, 38, 39],
  Kyushu: [40, 41, 42, 43, 44, 45, 46, 47],
};
const JP_CAPITALS = {
  1: 'Sapporo', 2: 'Aomori', 3: 'Morioka', 4: 'Sendai', 5: 'Akita', 6: 'Yamagata',
  7: 'Fukushima', 8: 'Mito', 9: 'Utsunomiya', 10: 'Maebashi', 11: 'Saitama', 12: 'Chiba',
  13: 'Tokyo', 14: 'Yokohama', 15: 'Niigata', 16: 'Toyama', 17: 'Kanazawa', 18: 'Fukui',
  19: 'Kofu', 20: 'Nagano', 21: 'Gifu', 22: 'Shizuoka', 23: 'Nagoya', 24: 'Tsu',
  25: 'Otsu', 26: 'Kyoto', 27: 'Osaka', 28: 'Kobe', 29: 'Nara', 30: 'Wakayama',
  31: 'Tottori', 32: 'Matsue', 33: 'Okayama', 34: 'Hiroshima', 35: 'Yamaguchi',
  36: 'Tokushima', 37: 'Takamatsu', 38: 'Matsuyama', 39: 'Kochi', 40: 'Fukuoka',
  41: 'Saga', 42: 'Nagasaki', 43: 'Kumamoto', 44: 'Oita', 45: 'Miyazaki',
  46: 'Kagoshima', 47: 'Naha',
};

function buildJapan() {
  const src = read('jp-pref.s.json');
  const regionOf = new Map();
  for (const region of Object.keys(JP_REGIONS))
    for (const id of JP_REGIONS[region]) regionOf.set(id, region);

  const features = src.features.map(f => {
    const p = f.properties;
    // "Kyoto Fu" -> "Kyoto", "Aomori Ken" -> "Aomori", "Hokkai Do" -> "Hokkaido"
    let name = p.nam.replace(/\s+(Ken|Fu|To|Do)$/i, '');
    if (/^Hokkai/i.test(p.nam)) name = 'Hokkaido';
    return {
      type: 'Feature',
      properties: {
        id: String(p.id).padStart(2, '0'),
        name: name,
        nameLocal: p.nam_ja,
        region: regionOf.get(p.id),
        capital: JP_CAPITALS[p.id],
      },
      geometry: f.geometry,
    };
  }).sort((a, b) => a.properties.id.localeCompare(b.properties.id));

  const fc = { type: 'FeatureCollection', features: features };
  emit('japan.js', 'DATA_JAPAN', { regions: Object.keys(JP_REGIONS), prefectures: fc });
  return fc;
}

/* ----------------------------------------------------------------- FRANCE */
function buildFrance() {
  const depGeo = read('fr-dep.s.json');
  const regGeo = read('fr-reg.s.json');
  const depMeta = new Map(read('fr-dep-meta.json').map(d => [d.code, d]));
  const regMeta = new Map(read('fr-reg-meta.json').map(r => [r.code, r]));

  const regions = {
    type: 'FeatureCollection',
    features: regGeo.features.map(f => ({
      type: 'Feature',
      properties: { id: f.properties.code, name: f.properties.nom },
      geometry: f.geometry,
    })).sort((a, b) => a.properties.name.localeCompare(b.properties.name, 'fr')),
  };

  const departments = {
    type: 'FeatureCollection',
    features: depGeo.features.map(f => {
      const m = depMeta.get(f.properties.code);
      const r = m && regMeta.get(m.region);
      return {
        type: 'Feature',
        properties: {
          id: f.properties.code,
          name: f.properties.nom,
          region: r ? r.nom : '',
          regionId: m ? m.region : '',
        },
        geometry: f.geometry,
      };
    }).sort((a, b) => a.properties.id.localeCompare(b.properties.id)),
  };

  const missing = departments.features.filter(f => !f.properties.region);
  if (missing.length)
    console.warn('  ! départements with no region: ' + missing.map(f => f.properties.id).join(','));

  emit('france.js', 'DATA_FRANCE', { regions: regions, departments: departments });
  return { regions: regions, departments: departments };
}

/* -------------------------------------------------------------- COUNTRY INFO */
/**
 * The plain reference card for a country: capital, money, size, who it touches.
 * mledoze/countries carries everything except population, which comes from the
 * World Bank so the figure is current rather than whatever year the static
 * dataset was frozen at.
 */
// Entities that ISO 3166 does not list (so mledoze has no row) and territories
// the World Bank does not report on. Figures are round approximations, and the
// UI does not claim otherwise.
const MANUAL_INFO = {
  XKX: {
    capital: 'Pristina', currency: { code: 'EUR', name: 'Euro', symbol: '€' },
    area: 10887, languages: ['Albanian', 'Serbian'], phone: '+383',
    population: 1600000, popYear: '2024 est.', borders: ['ALB', 'MKD', 'MNE', 'SRB'],
    landlocked: true,
  },
  XNC: {
    capital: 'North Nicosia', currency: { code: 'TRY', name: 'Turkish lira', symbol: '₺' },
    area: 3355, languages: ['Turkish'], phone: '+90',
    population: 390000, popYear: '2024 est.', borders: ['CYP'], landlocked: false,
  },
  XSO: {
    capital: 'Hargeisa', currency: { code: 'SLS', name: 'Somaliland shilling', symbol: 'Sl' },
    area: 176120, languages: ['Somali', 'Arabic', 'English'], phone: '+252',
    population: 5700000, popYear: '2024 est.', borders: ['DJI', 'ETH', 'SOM'],
    landlocked: false,
  },
};
// Populations the World Bank does not publish
const MANUAL_POP = {
  TWN: { value: 23400000, year: '2025 est.' },
  ESH: { value: 600000, year: '2024 est.' },
  FLK: { value: 3700, year: '2021 census' },
};

function buildCountryInfo(worldFC) {
  const src = read('countries-mledoze.json');
  const byCca3 = new Map(src.map(c => [c.cca3, c]));

  const wb = read('worldbank-pop.json')[1] || [];
  const pop = new Map();
  for (const row of wb) {
    if (row.countryiso3code && row.value) {
      pop.set(row.countryiso3code, { value: Math.round(row.value), year: row.date });
    }
  }

  const out = {};
  const missing = [];
  for (const f of worldFC.features) {
    const id = f.properties.id;
    if (MANUAL_INFO[id]) { out[id] = MANUAL_INFO[id]; continue; }
    const c = byCca3.get(id);
    if (!c) { missing.push(f.properties.name); continue; }

    const cur = Object.entries(c.currencies || {})[0];
    const p = pop.get(id) || MANUAL_POP[id];
    const entry = {
      capital: (c.capital && c.capital[0]) || null,
      currency: cur ? { code: cur[0], name: cur[1].name, symbol: cur[1].symbol || '' } : null,
      area: c.area || null,
      languages: Object.values(c.languages || {}),
      tld: (c.tld && c.tld[0]) || null,
      borders: c.borders || [],
      landlocked: !!c.landlocked,
    };
    if (p) { entry.population = p.value; entry.popYear = p.year; }
    if (c.idd && c.idd.root) {
      entry.phone = c.idd.root + ((c.idd.suffixes && c.idd.suffixes.length === 1) ? c.idd.suffixes[0] : '');
    }
    out[id] = entry;
  }
  if (missing.length) console.warn('  ! no reference data for: ' + missing.join(', '));
  const noPop = Object.keys(out).filter(k => !out[k].population);
  if (noPop.length) console.warn('  ! no population for: ' + noPop.join(', '));

  emit('countries.js', 'DATA_COUNTRY_INFO', out);
  return out;
}

/* ----------------------------------------------------------------- CITIES */
const G = { name: 1, ascii: 2, lat: 4, lon: 5, fcode: 7, country: 8, pop: 14 };

function haversine(a, b) {
  const R = 6371, rad = d => d * Math.PI / 180;
  const dLat = rad(b.lat - a.lat), dLon = rad(b.lon - a.lon);
  const h = Math.sin(dLat / 2) ** 2
    + Math.cos(rad(a.lat)) * Math.cos(rad(b.lat)) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}

function buildCities(japanFC, franceDepFC) {
  const lines = fs.readFileSync(path.join(RAW, 'jpfr.txt'), 'utf8').split('\n').filter(Boolean);
  // GeoNames column 1 keeps diacritics (Nîmes, Besançon); column 2 is stripped
  // ASCII, which we keep only for accent-insensitive matching.
  const RENAME = { 'Nara-shi': 'Nara', 'Dunkirk': 'Dunkerque' };
  const rows = lines.map(l => l.split('\t')).map(c => ({
    name: RENAME[c[G.name]] || c[G.name],
    ascii: c[G.ascii],
    lat: +c[G.lat], lon: +c[G.lon],
    fcode: c[G.fcode], country: c[G.country], pop: +c[G.pop],
  }));

  // Tokyo's special wards and the big-city "-shi" duplicates are separate rows
  // in GeoNames; they would stack on top of each other on a city map.
  const DENY = new Set(['Shinjuku', 'Shibuya', 'Chiyoda', 'Chuo', 'Minato', 'Taito', 'Sumida',
    'Koto', 'Shinagawa', 'Meguro', 'Ota', 'Setagaya', 'Nakano', 'Suginami', 'Toshima', 'Kita',
    'Arakawa', 'Itabashi', 'Nerima', 'Adachi', 'Katsushika', 'Edogawa', 'Bunkyo', 'Ōta',
    'Yokohama Shi', 'Osaka Shi', 'Nagoya Shi', 'Sakai Shi', 'Marne La Vallee', 'Marne La Vallée',
    'Boulogne-Billancourt', 'Montreuil', 'Argenteuil', 'Saint-Denis', 'Nanterre', 'Vitry-sur-Seine',
    'Créteil', 'Asnières-sur-Seine', 'Courbevoie', 'Colombes', 'Aulnay-sous-Bois', 'Rueil-Malmaison',
    'Champigny-sur-Marne', 'Antony', 'Neuilly-sur-Seine', 'Levallois-Perret', 'Issy-les-Moulineaux',
    'Cergy', 'Pantin', 'Ivry-sur-Seine', 'Clichy', 'Sarcelles', 'Drancy', 'Noisy-le-Grand',
    'Villeurbanne', 'Aubervilliers', 'La Courneuve', 'Épinay-sur-Seine', 'Bobigny',
    'Maisons-Alfort', 'Meaux', 'Chelles', 'Fontenay-sous-Bois', 'Bondy', 'Le Blanc-Mesnil',
    'Sevran', 'Saint-Maur-des-Fossés', 'Vincennes', 'Massy', 'Villejuif', 'Clamart',
    'Bourg-la-Reine', 'Suresnes', 'Puteaux', 'Malakoff', 'Gennevilliers', 'Bagneux',
    // GeoNames duplicates that outrank the city they belong to
    'Aihara', 'Saint-Quentin-en-Yvelines',
  ]);

  // Keep real settlements only: PPLX is a city district, PPLL a loose locality.
  const OK_FCODE = new Set(['PPL', 'PPLA', 'PPLA2', 'PPLA3', 'PPLA4', 'PPLC', 'PPLG']);

  function pick(cc, poly, keyProp, limit, minPop) {
    const cand = rows
      .filter(r => r.country === cc && r.pop >= minPop && OK_FCODE.has(r.fcode)
        && !DENY.has(r.name) && !DENY.has(r.ascii))
      .sort((a, b) => b.pop - a.pop);

    const chosen = [];
    for (const c of cand) {
      if (chosen.length >= limit) break;
      // collapse near-duplicates: one conurbation listed under several names
      if (chosen.some(o => haversine(o, c) < 15)) continue;
      const owner = poly.features.find(f => d3.geoContains(f, [c.lon, c.lat]));
      if (!owner) continue; // offshore, or outside the mapped area
      const entry = {
        name: c.name,
        lat: +c.lat.toFixed(4), lon: +c.lon.toFixed(4), pop: c.pop,
        parent: owner.properties.name,
      };
      entry[keyProp] = owner.properties.id;
      if (c.ascii && c.ascii !== c.name) entry.ascii = c.ascii;
      chosen.push(entry);
    }
    return chosen;
  }

  const jp = pick('JP', japanFC, 'prefecture', 55, 150000);
  const fr = pick('FR', franceDepFC, 'department', 55, 55000);
  emit('cities.js', 'DATA_CITIES', { JP: jp, FR: fr });
  return { jp: jp, fr: fr };
}

/* -------------------------------------------------------------------- run */
console.log('Building data files...');
const world = buildWorld();
buildCountryInfo(world);
const jp = buildJapan();
const fr = buildFrance();
const cities = buildCities(jp, fr.departments);
const last = a => a[a.length - 1];
console.log('\nJapan cities:  ' + cities.jp.length + '  (top ' + cities.jp[0].name
  + ', smallest ' + last(cities.jp).name + ' @ ' + last(cities.jp).pop.toLocaleString() + ')');
console.log('France cities: ' + cities.fr.length + '  (top ' + cities.fr[0].name
  + ', smallest ' + last(cities.fr).name + ' @ ' + last(cities.fr).pop.toLocaleString() + ')');
