/*
 * build-data.js — turns the raw sources in tools/raw/ into the browser data
 * files in data/. Everything is emitted as `window.DATA_* = ...` so the app
 * works from file:// with no server and no build step.
 *
 * Run with:  node tools/build-data.js
 */
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const RAW = path.join(__dirname, 'raw');
const OUT = path.join(__dirname, '..', 'data');
const read = f => JSON.parse(fs.readFileSync(path.join(RAW, f), 'utf8'));

// --- load d3-geo + topojson into a clean context (their UMD wrappers take the
// CommonJS branch under node, which breaks the d3-array dependency) ---------
const ctx = vm.createContext({});
for (const f of ['d3-array.min.js', 'd3-geo.min.js', 'topojson-client.min.js'])
  vm.runInContext(fs.readFileSync(path.join(__dirname, '..', 'js', 'vendor', f), 'utf8'), ctx);
const d3 = ctx.d3, topojson = ctx.topojson;

function emit(file, varName, value) {
  const body = '// Generated by tools/build-data.js — do not edit by hand.\n'
    + 'window.' + varName + ' = ' + JSON.stringify(value) + ';\n';
  fs.writeFileSync(path.join(OUT, file), body);
  console.log('  data/' + file.padEnd(16) + (body.length / 1024).toFixed(0).padStart(5) + ' KB  ' + varName);
}

function round(features, prec) {
  const r = n => Math.round(n * 10 ** prec) / 10 ** prec;
  const walk = c => Array.isArray(c[0]) ? c.map(walk) : [r(c[0]), r(c[1])];
  for (const f of features) f.geometry.coordinates = walk(f.geometry.coordinates);
}

/* ------------------------------------------------------------ ENGLISH NAMES */
/**
 * Every label in the app is rendered in the Latin alphabet without diacritics,
 * because "Côtes-d'Armor" and "Kōriyama" are a wall to anyone who does not
 * already read French or romanised Japanese.
 *
 * Two rules, in order:
 *   1. If English genuinely has its own name for the place, use it. Brittany,
 *      not Bretagne.
 *   2. Otherwise strip the accents and leave the name alone. There is no
 *      English word for Ille-et-Vilaine, and inventing one would make the
 *      place harder to look up rather than easier.
 *
 * The original spelling is kept as `nameLocal` and shown on the info card, so
 * nothing is actually lost.
 */
const EXONYM = {
  // French regions with established English names
  'Bretagne': 'Brittany',
  'Normandie': 'Normandy',
  'Corse': 'Corsica',
  'Occitanie': 'Occitania',
  'Bourgogne-Franche-Comté': 'Burgundy-Franche-Comte',
  // French cities English has its own spelling for
  'Dunkerque': 'Dunkirk',
  'Dunkirk': 'Dunkirk',
  // the one country name in the world set that is not already plain English
  "Côte d'Ivoire": 'Ivory Coast',
};

function english(name) {
  if (!name) return name;
  if (EXONYM[name]) return EXONYM[name];
  return name
    .normalize('NFD').replace(/[̀-ͯ]/g, '')  // drop combining accents
    .replace(/[‘’]/g, "'")                   // curly quotes -> ASCII
    .replace(/[–—]/g, '-');                  // en/em dash -> hyphen
}

/**
 * { name, nameLocal } with nameLocal present only when it is worth showing.
 *
 * Punctuation is normalised before the comparison, so Xi’an does not end up
 * carrying "Xi’an" as its local name — the curly apostrophe is the only
 * difference and reprinting it teaches nobody anything. Ürümqi keeps Ürümqi.
 */
function label(original) {
  const tidy = String(original)
    .replace(/[‘’]/g, "'")
    .replace(/[–—]/g, '-');
  const name = english(original);
  return name === tidy ? { name: name } : { name: name, nameLocal: original };
}

/* ------------------------------------------------------- SIMPLIFY GEOMETRY */
function perpDist(p, a, b) {
  const [x, y] = p, [x1, y1] = a, [x2, y2] = b;
  const dx = x2 - x1, dy = y2 - y1;
  if (dx === 0 && dy === 0) return Math.hypot(x - x1, y - y1);
  const t = Math.max(0, Math.min(1, ((x - x1) * dx + (y - y1) * dy) / (dx * dx + dy * dy)));
  return Math.hypot(x - (x1 + t * dx), y - (y1 + t * dy));
}

function dp(pts, eps) {
  if (pts.length < 3) return pts;
  let maxD = 0, idx = 0;
  for (let i = 1; i < pts.length - 1; i++) {
    const d = perpDist(pts[i], pts[0], pts[pts.length - 1]);
    if (d > maxD) { maxD = d; idx = i; }
  }
  if (maxD <= eps) return [pts[0], pts[pts.length - 1]];
  return dp(pts.slice(0, idx + 1), eps).slice(0, -1).concat(dp(pts.slice(idx), eps));
}

/** Douglas-Peucker every ring, dropping rings that collapse below `minArea`. */
function thin(features, eps, minArea) {
  const ringArea = r => {
    let a = 0;
    for (let i = 0, j = r.length - 1; i < r.length; j = i++) a += r[j][0] * r[i][1] - r[i][0] * r[j][1];
    return Math.abs(a / 2);
  };
  const ring = r => {
    let out = dp(r, eps);
    if (out.length < 4) return null;
    const f = out[0], l = out[out.length - 1];
    if (f[0] !== l[0] || f[1] !== l[1]) out = out.concat([[f[0], f[1]]]);
    return out.length >= 4 ? out : null;
  };
  const poly = p => {
    const outer = ring(p[0]);
    if (!outer || ringArea(outer) < minArea) return null;
    return [outer].concat(p.slice(1).map(ring).filter(h => h && ringArea(h) >= minArea));
  };
  for (const f of features) {
    const g = f.geometry;
    if (g.type === 'Polygon') {
      const p = poly(g.coordinates);
      if (p) g.coordinates = p;
    } else if (g.type === 'MultiPolygon') {
      const ps = g.coordinates.map(poly).filter(Boolean);
      if (ps.length === 1) f.geometry = { type: 'Polygon', coordinates: ps[0] };
      else if (ps.length) g.coordinates = ps;
      // nothing survived: keep the original rather than lose the feature
    }
  }
}

/* ------------------------------------------------------------------ WORLD */
function buildWorld() {
  const topo = read('world-110m.json');
  const fc = topojson.feature(topo, topo.objects.countries);
  const iso = read('iso.json');
  const byNum = new Map(iso.map(r => [String(+r['country-code']), r]));

  // world-atlas abbreviates some names; spell them out for quiz prompts
  const NAME_FIX = {
    'Dem. Rep. Congo': 'DR Congo',
    'Congo': 'Republic of the Congo',
    'Central African Rep.': 'Central African Republic',
    'Dominican Rep.': 'Dominican Republic',
    'Eq. Guinea': 'Equatorial Guinea',
    'S. Sudan': 'South Sudan',
    'Bosnia and Herz.': 'Bosnia and Herzegovina',
    'Solomon Is.': 'Solomon Islands',
    'Falkland Is.': 'Falkland Islands',
    'Fr. S. Antarctic Lands': 'French Southern Territories',
    'W. Sahara': 'Western Sahara',
    'N. Cyprus': 'Northern Cyprus',
    'United States of America': 'United States',
    'Central African Rep': 'Central African Republic',
  };
  // continent info for entries ISO 3166 does not assign
  const EXTRA = {
    'Somaliland': { region: 'Africa', subregion: 'Sub-Saharan Africa', iso2: 'XS', id: 'XSO' },
    'Kosovo': { region: 'Europe', subregion: 'Southern Europe', iso2: 'XK', id: 'XKX' },
    'Northern Cyprus': { region: 'Asia', subregion: 'Western Asia', iso2: 'XN', id: 'XNC' },
  };
  // ISO 3166 leaves Taiwan's region fields blank; the quiz needs a continent
  const REGION_FIX = { TWN: { region: 'Asia', subregion: 'Eastern Asia' } };

  const features = [];
  for (const f of fc.features) {
    const meta = byNum.get(String(+f.id));
    const rawName = f.properties.name;
    const name = NAME_FIX[rawName] || rawName;
    const extra = EXTRA[name];
    if (!meta && !extra) { console.warn('  ! no ISO metadata for ' + rawName); continue; }
    const id = meta ? meta['alpha-3'] : extra.id;
    const fix = REGION_FIX[id];
    features.push({
      type: 'Feature',
      properties: Object.assign(label(name), {
        id: id,
        iso2: meta ? meta['alpha-2'] : extra.iso2,
        region: (fix && fix.region) || (meta ? meta.region : extra.region),
        subregion: (fix && fix.subregion) || (meta ? meta['sub-region'] : extra.subregion),
      }),
      geometry: f.geometry,
    });
  }
  // Antarctica is not a country-quiz target
  const out = features.filter(f => f.properties.id !== 'ATA');
  round(out, 2);
  out.sort((a, b) => a.properties.name.localeCompare(b.properties.name));
  emit('world.js', 'DATA_WORLD', { type: 'FeatureCollection', features: out });
  return { type: 'FeatureCollection', features: out };
}

/* ------------------------------------------------------------------ JAPAN */
const JP_REGIONS = {
  Hokkaido: [1],
  Tohoku: [2, 3, 4, 5, 6, 7],
  Kanto: [8, 9, 10, 11, 12, 13, 14],
  Chubu: [15, 16, 17, 18, 19, 20, 21, 22, 23],
  Kansai: [24, 25, 26, 27, 28, 29, 30],
  Chugoku: [31, 32, 33, 34, 35],
  Shikoku: [36, 37, 38, 39],
  Kyushu: [40, 41, 42, 43, 44, 45, 46, 47],
};
const JP_CAPITALS = {
  1: 'Sapporo', 2: 'Aomori', 3: 'Morioka', 4: 'Sendai', 5: 'Akita', 6: 'Yamagata',
  7: 'Fukushima', 8: 'Mito', 9: 'Utsunomiya', 10: 'Maebashi', 11: 'Saitama', 12: 'Chiba',
  13: 'Tokyo', 14: 'Yokohama', 15: 'Niigata', 16: 'Toyama', 17: 'Kanazawa', 18: 'Fukui',
  19: 'Kofu', 20: 'Nagano', 21: 'Gifu', 22: 'Shizuoka', 23: 'Nagoya', 24: 'Tsu',
  25: 'Otsu', 26: 'Kyoto', 27: 'Osaka', 28: 'Kobe', 29: 'Nara', 30: 'Wakayama',
  31: 'Tottori', 32: 'Matsue', 33: 'Okayama', 34: 'Hiroshima', 35: 'Yamaguchi',
  36: 'Tokushima', 37: 'Takamatsu', 38: 'Matsuyama', 39: 'Kochi', 40: 'Fukuoka',
  41: 'Saga', 42: 'Nagasaki', 43: 'Kumamoto', 44: 'Oita', 45: 'Miyazaki',
  46: 'Kagoshima', 47: 'Naha',
};

function buildJapan() {
  const src = read('jp-pref.s.json');
  const regionOf = new Map();
  for (const region of Object.keys(JP_REGIONS))
    for (const id of JP_REGIONS[region]) regionOf.set(id, region);

  const features = src.features.map(f => {
    const p = f.properties;
    // "Kyoto Fu" -> "Kyoto", "Aomori Ken" -> "Aomori", "Hokkai Do" -> "Hokkaido"
    let name = p.nam.replace(/\s+(Ken|Fu|To|Do)$/i, '');
    if (/^Hokkai/i.test(p.nam)) name = 'Hokkaido';
    return {
      type: 'Feature',
      properties: {
        id: String(p.id).padStart(2, '0'),
        name: name,
        nameLocal: p.nam_ja,
        region: regionOf.get(p.id),
        capital: JP_CAPITALS[p.id],
      },
      geometry: f.geometry,
    };
  }).sort((a, b) => a.properties.id.localeCompare(b.properties.id));

  const fc = { type: 'FeatureCollection', features: features };
  emit('japan.js', 'DATA_JAPAN', { regions: Object.keys(JP_REGIONS), prefectures: fc });
  return fc;
}

/* ----------------------------------------------------------------- FRANCE */
function buildFrance() {
  const depGeo = read('fr-dep.s.json');
  const regGeo = read('fr-reg.s.json');
  const depMeta = new Map(read('fr-dep-meta.json').map(d => [d.code, d]));
  const regMeta = new Map(read('fr-reg-meta.json').map(r => [r.code, r]));

  const regions = {
    type: 'FeatureCollection',
    features: regGeo.features.map(f => ({
      type: 'Feature',
      properties: Object.assign(label(f.properties.nom), { id: f.properties.code }),
      geometry: f.geometry,
    })).sort((a, b) => a.properties.name.localeCompare(b.properties.name)),
  };

  const departments = {
    type: 'FeatureCollection',
    features: depGeo.features.map(f => {
      const m = depMeta.get(f.properties.code);
      const r = m && regMeta.get(m.region);
      return {
        type: 'Feature',
        properties: Object.assign(label(f.properties.nom), {
          id: f.properties.code,
          region: r ? english(r.nom) : '',
          regionId: m ? m.region : '',
        }),
        geometry: f.geometry,
      };
    }).sort((a, b) => a.properties.id.localeCompare(b.properties.id)),
  };

  const missing = departments.features.filter(f => !f.properties.region);
  if (missing.length)
    console.warn('  ! départements with no region: ' + missing.map(f => f.properties.id).join(','));

  emit('france.js', 'DATA_FRANCE', { regions: regions, departments: departments });
  return { regions: regions, departments: departments };
}

/* -------------------------------------------------------------- COUNTRY INFO */
/**
 * The plain reference card for a country: capital, money, size, who it touches.
 * mledoze/countries carries everything except population, which comes from the
 * World Bank so the figure is current rather than whatever year the static
 * dataset was frozen at.
 */
// Entities that ISO 3166 does not list (so mledoze has no row) and territories
// the World Bank does not report on. Figures are round approximations, and the
// UI does not claim otherwise.
const MANUAL_INFO = {
  XKX: {
    capital: 'Pristina', currency: { code: 'EUR', name: 'Euro', symbol: '€' },
    area: 10887, languages: ['Albanian', 'Serbian'], phone: '+383',
    population: 1600000, popYear: '2024 est.', borders: ['ALB', 'MKD', 'MNE', 'SRB'],
    landlocked: true,
  },
  XNC: {
    capital: 'North Nicosia', currency: { code: 'TRY', name: 'Turkish lira', symbol: '₺' },
    area: 3355, languages: ['Turkish'], phone: '+90',
    population: 390000, popYear: '2024 est.', borders: ['CYP'], landlocked: false,
  },
  XSO: {
    capital: 'Hargeisa', currency: { code: 'SLS', name: 'Somaliland shilling', symbol: 'Sl' },
    area: 176120, languages: ['Somali', 'Arabic', 'English'], phone: '+252',
    population: 5700000, popYear: '2024 est.', borders: ['DJI', 'ETH', 'SOM'],
    landlocked: false,
  },
};
// Populations the World Bank does not publish
const MANUAL_POP = {
  TWN: { value: 23400000, year: '2025 est.' },
  ESH: { value: 600000, year: '2024 est.' },
  FLK: { value: 3700, year: '2021 census' },
};

function buildCountryInfo(worldFC) {
  const src = read('countries-mledoze.json');
  const byCca3 = new Map(src.map(c => [c.cca3, c]));

  const wb = read('worldbank-pop.json')[1] || [];
  const pop = new Map();
  for (const row of wb) {
    if (row.countryiso3code && row.value) {
      pop.set(row.countryiso3code, { value: Math.round(row.value), year: row.date });
    }
  }

  const out = {};
  const missing = [];
  for (const f of worldFC.features) {
    const id = f.properties.id;
    if (MANUAL_INFO[id]) { out[id] = MANUAL_INFO[id]; continue; }
    const c = byCca3.get(id);
    if (!c) { missing.push(f.properties.name); continue; }

    const cur = Object.entries(c.currencies || {})[0];
    const p = pop.get(id) || MANUAL_POP[id];
    const entry = {
      capital: (c.capital && c.capital[0]) || null,
      currency: cur ? { code: cur[0], name: cur[1].name, symbol: cur[1].symbol || '' } : null,
      area: c.area || null,
      languages: Object.values(c.languages || {}),
      tld: (c.tld && c.tld[0]) || null,
      borders: c.borders || [],
      landlocked: !!c.landlocked,
    };
    if (p) { entry.population = p.value; entry.popYear = p.year; }
    if (c.idd && c.idd.root) {
      entry.phone = c.idd.root + ((c.idd.suffixes && c.idd.suffixes.length === 1) ? c.idd.suffixes[0] : '');
    }
    out[id] = entry;
  }
  if (missing.length) console.warn('  ! no reference data for: ' + missing.join(', '));
  const noPop = Object.keys(out).filter(k => !out[k].population);
  if (noPop.length) console.warn('  ! no population for: ' + noPop.join(', '));

  emit('countries.js', 'DATA_COUNTRY_INFO', out);
  return out;
}

/* ------------------------------------------------------------------ CHINA */
/*
 * The 31 province-level divisions of mainland China: 22 provinces, 5
 * autonomous regions and 4 municipalities. Hong Kong and Macau are separate
 * top-level units in Natural Earth and Taiwan is already its own country in
 * the world deck, so none of the three appear here.
 *
 * Grouped into the six conventional regions Chinese geography teaching uses.
 */
const CN_REGIONS = {
  'North China': ['BJ', 'TJ', 'HE', 'SX', 'NM'],
  'Northeast': ['LN', 'JL', 'HL'],
  'East China': ['SH', 'JS', 'ZJ', 'AH', 'FJ', 'JX', 'SD'],
  'South Central': ['HA', 'HB', 'HN', 'GD', 'GX', 'HI'],
  'Southwest': ['CQ', 'SC', 'GZ', 'YN', 'XZ'],
  'Northwest': ['SN', 'GS', 'QH', 'NX', 'XJ'],
};
const CN_CAPITALS = {
  AH: 'Hefei', BJ: 'Beijing', CQ: 'Chongqing', FJ: 'Fuzhou', GD: 'Guangzhou',
  GS: 'Lanzhou', GX: 'Nanning', GZ: 'Guiyang', HA: 'Zhengzhou', HB: 'Wuhan',
  HE: 'Shijiazhuang', HI: 'Haikou', HL: 'Harbin', HN: 'Changsha', JL: 'Changchun',
  JS: 'Nanjing', JX: 'Nanchang', LN: 'Shenyang', NM: 'Hohhot', NX: 'Yinchuan',
  QH: 'Xining', SC: 'Chengdu', SD: 'Jinan', SH: 'Shanghai', SN: "Xi'an",
  SX: 'Taiyuan', TJ: 'Tianjin', XJ: 'Urumqi', XZ: 'Lhasa', YN: 'Kunming',
  ZJ: 'Hangzhou',
};

function buildChina() {
  const src = JSON.parse(fs.readFileSync(path.join(RAW, 'ne50-admin1.geojson'), 'utf8'));
  const regionOf = new Map();
  for (const region of Object.keys(CN_REGIONS))
    for (const id of CN_REGIONS[region]) regionOf.set(id, region);

  const features = src.features
    .filter(f => f.properties.adm0_a3 === 'CHN' && f.properties.iso_3166_2)
    .map(f => {
      const p = f.properties;
      const id = p.iso_3166_2.replace(/^CN-/, '');
      return {
        type: 'Feature',
        properties: Object.assign(label(p.name_en), {
          id: id,
          nameLocal: p.name_zh || undefined,
          region: regionOf.get(id),
          capital: CN_CAPITALS[id],
          kind: p.type_en,
        }),
        geometry: f.geometry,
      };
    })
    .sort((a, b) => a.properties.name.localeCompare(b.properties.name));

  const ungrouped = features.filter(f => !f.properties.region);
  if (ungrouped.length)
    console.warn('  ! China divisions with no region: '
      + ungrouped.map(f => f.properties.id).join(','));

  // Cities are assigned against the *unsimplified* outlines. Thinning moves a
  // coastline by up to a kilometre, which is enough to push Shenzhen outside
  // Guangdong and drop China's fourth-largest city from the list entirely.
  const raw = JSON.parse(JSON.stringify({ type: 'FeatureCollection', features: features }));

  thin(features, 0.012, 0.004);
  round(features, 3);
  const fc = { type: 'FeatureCollection', features: features };
  emit('china.js', 'DATA_CHINA', { regions: Object.keys(CN_REGIONS), provinces: fc });
  return { display: fc, raw: raw };
}

/* ----------------------------------------------------------------- CITIES */
const G = { name: 1, ascii: 2, lat: 4, lon: 5, fcode: 7, country: 8, pop: 14 };

function haversine(a, b) {
  const R = 6371, rad = d => d * Math.PI / 180;
  const dLat = rad(b.lat - a.lat), dLon = rad(b.lon - a.lon);
  const h = Math.sin(dLat / 2) ** 2
    + Math.cos(rad(a.lat)) * Math.cos(rad(b.lat)) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}

/**
 * Rough km from a point to a feature, 0 if inside its bounding box.
 *
 * Used only to rescue a city that falls just outside a generalised outline.
 * Distance to the *centroid* is not good enough: Shantou sits in far eastern
 * Guangdong, and Fujian's centroid is almost exactly as close, so a centroid
 * test can hand the city to the wrong province. A bounding box puts Shantou
 * inside Guangdong and 17 km outside Fujian, which is the right answer.
 */
function distToBoxKm(feature, lon, lat) {
  const [[w, s], [e, n]] = d3.geoBounds(feature);
  const dLon = Math.max(w - lon, 0, lon - e);
  const dLat = Math.max(s - lat, 0, lat - n);
  return Math.hypot(dLon * Math.cos(lat * Math.PI / 180), dLat) * 111;
}

function nearestFeature(poly, lon, lat, maxKm) {
  let best = null, bestD = Infinity;
  for (const f of poly.features) {
    const d = distToBoxKm(f, lon, lat);
    if (d < bestD) { bestD = d; best = f; }
  }
  return bestD <= maxKm ? best : null;
}

function buildCities(japanFC, franceDepFC, chinaFC) {
  const lines = ['jpfr.txt', 'cn-cities.txt']
    .flatMap(f => fs.readFileSync(path.join(RAW, f), 'utf8').split('\n'))
    .filter(Boolean);
  // GeoNames column 1 keeps the local spelling (Nîmes, Ōita, Ürümqi); column 2
  // is its own stripped ASCII, which we keep only for accent-blind matching.
  const RENAME = { 'Nara-shi': 'Nara' };
  const rows = lines.map(l => l.split('\t')).map(c => {
    const local = RENAME[c[G.name]] || c[G.name];
    return Object.assign(label(local), {
      ascii: c[G.ascii],
      lat: +c[G.lat], lon: +c[G.lon],
      fcode: c[G.fcode], country: c[G.country], pop: +c[G.pop],
    });
  });

  // Tokyo's special wards and the big-city "-shi" duplicates are separate rows
  // in GeoNames; they would stack on top of each other on a city map.
  const DENY = new Set(['Shinjuku', 'Shibuya', 'Chiyoda', 'Chuo', 'Minato', 'Taito', 'Sumida',
    'Koto', 'Shinagawa', 'Meguro', 'Ota', 'Setagaya', 'Nakano', 'Suginami', 'Toshima', 'Kita',
    'Arakawa', 'Itabashi', 'Nerima', 'Adachi', 'Katsushika', 'Edogawa', 'Bunkyo', 'Ōta',
    'Yokohama Shi', 'Osaka Shi', 'Nagoya Shi', 'Sakai Shi', 'Marne La Vallee', 'Marne La Vallée',
    'Boulogne-Billancourt', 'Montreuil', 'Argenteuil', 'Saint-Denis', 'Nanterre', 'Vitry-sur-Seine',
    'Créteil', 'Asnières-sur-Seine', 'Courbevoie', 'Colombes', 'Aulnay-sous-Bois', 'Rueil-Malmaison',
    'Champigny-sur-Marne', 'Antony', 'Neuilly-sur-Seine', 'Levallois-Perret', 'Issy-les-Moulineaux',
    'Cergy', 'Pantin', 'Ivry-sur-Seine', 'Clichy', 'Sarcelles', 'Drancy', 'Noisy-le-Grand',
    'Villeurbanne', 'Aubervilliers', 'La Courneuve', 'Épinay-sur-Seine', 'Bobigny',
    'Maisons-Alfort', 'Meaux', 'Chelles', 'Fontenay-sous-Bois', 'Bondy', 'Le Blanc-Mesnil',
    'Sevran', 'Saint-Maur-des-Fossés', 'Vincennes', 'Massy', 'Villejuif', 'Clamart',
    'Bourg-la-Reine', 'Suresnes', 'Puteaux', 'Malakoff', 'Gennevilliers', 'Bagneux',
    // GeoNames duplicates that outrank the city they belong to
    'Aihara', 'Saint-Quentin-en-Yvelines',
  ]);

  // Keep real settlements only: PPLX is a city district, PPLL a loose locality.
  const OK_FCODE = new Set(['PPL', 'PPLA', 'PPLA2', 'PPLA3', 'PPLA4', 'PPLC', 'PPLG']);

  function pick(cc, poly, keyProp, limit, minPop, mergeKm) {
    const cand = rows
      .filter(r => r.country === cc && r.pop >= minPop && OK_FCODE.has(r.fcode)
        && !DENY.has(r.name) && !DENY.has(r.ascii))
      .sort((a, b) => b.pop - a.pop);

    const chosen = [];
    for (const c of cand) {
      if (chosen.length >= limit) break;
      // collapse near-duplicates: one conurbation listed under several names
      if (chosen.some(o => haversine(o, c) < (mergeKm || 15))) continue;
      // A coastal or border city can fall just outside a generalised outline.
      let owner = poly.features.find(f => d3.geoContains(f, [c.lon, c.lat]))
        || nearestFeature(poly, c.lon, c.lat, 25);
      if (!owner) continue; // genuinely offshore, or outside the mapped area
      const entry = {
        name: c.name,
        lat: +c.lat.toFixed(4), lon: +c.lon.toFixed(4), pop: c.pop,
        parent: owner.properties.name,
      };
      entry[keyProp] = owner.properties.id;
      if (c.nameLocal) entry.nameLocal = c.nameLocal;
      chosen.push(entry);
    }
    return chosen;
  }

  /**
   * China is picked from a named list rather than by population rank.
   *
   * GeoNames' Chinese population figures are prefecture-level administrative
   * totals, not urban populations, so ranking by them is badly skewed: the
   * record for Wuzhong carries the whole of Ningxia's 7.2 million, which put a
   * small city ahead of Qingdao, while genuinely major cities sat below the
   * cut. The list below is the 31 province-level capitals plus the largest
   * non-capital cities — the ones actually worth learning. Coordinates and
   * populations still come from GeoNames.
   */
  const CN_CITY_LIST = [
    // the four municipalities and every provincial capital
    'Beijing', 'Shanghai', 'Chongqing', 'Tianjin',
    'Shijiazhuang', 'Taiyuan', 'Hohhot', 'Shenyang', 'Changchun', 'Harbin',
    'Nanjing', 'Hangzhou', 'Hefei', 'Fuzhou', 'Nanchang', 'Jinan', 'Zhengzhou',
    'Wuhan', 'Changsha', 'Guangzhou', 'Nanning', 'Haikou', 'Chengdu', 'Guiyang',
    'Kunming', 'Lhasa', "Xi'an", 'Lanzhou', 'Xining', 'Yinchuan', 'Urumqi',
    // major non-capitals
    'Shenzhen', 'Dongguan', 'Foshan', 'Zhuhai', 'Shantou', 'Suzhou', 'Wuxi',
    'Xuzhou', 'Ningbo', 'Wenzhou', 'Qingdao', 'Yantai', 'Dalian', 'Xiamen',
    'Quanzhou', 'Luoyang', 'Yichang', 'Baotou', 'Tangshan', 'Datong',
    'Kashgar', 'Sanya', 'Guilin', 'Handan',
  ];

  function pickNamed(cc, poly, keyProp, names) {
    const byName = new Map();
    for (const r of rows) {
      if (r.country !== cc) continue;
      const prev = byName.get(r.name);
      if (!prev || r.pop > prev.pop) byName.set(r.name, r);   // keep the biggest
    }
    const out = [], missing = [];
    for (const wanted of names) {
      const c = byName.get(wanted);
      if (!c) { missing.push(wanted); continue; }
      const owner = poly.features.find(f => d3.geoContains(f, [c.lon, c.lat]))
        || nearestFeature(poly, c.lon, c.lat, 60);
      if (!owner) { missing.push(wanted + ' (no division)'); continue; }
      const entry = {
        name: c.name,
        lat: +c.lat.toFixed(4), lon: +c.lon.toFixed(4), pop: c.pop,
        parent: owner.properties.name,
      };
      entry[keyProp] = owner.properties.id;
      if (c.nameLocal) entry.nameLocal = c.nameLocal;
      out.push(entry);
    }
    if (missing.length) console.warn('  ! ' + cc + ' cities not matched: ' + missing.join(', '));
    return out.sort((a, b) => b.pop - a.pop);
  }

  const jp = pick('JP', japanFC, 'prefecture', 55, 150000);
  const fr = pick('FR', franceDepFC, 'department', 55, 55000);
  const cn = pickNamed('CN', chinaFC, 'province', CN_CITY_LIST);
  emit('cities.js', 'DATA_CITIES', { JP: jp, FR: fr, CN: cn });
  return { jp: jp, fr: fr, cn: cn };
}

/* -------------------------------------------------------------------- run */
console.log('Building data files...');
const world = buildWorld();
buildCountryInfo(world);
const jp = buildJapan();
const fr = buildFrance();
const cn = buildChina();
const cities = buildCities(jp, fr.departments, cn.raw);
const last = a => a[a.length - 1];
for (const [label_, list] of [['Japan', cities.jp], ['France', cities.fr], ['China', cities.cn]]) {
  console.log('\n' + label_ + ' cities: ' + list.length + '  (top ' + list[0].name
    + ', smallest ' + last(list).name + ' @ ' + last(list).pop.toLocaleString('en-US') + ')');
}
